繁化 SlimefunItems.java
SlimeTraditionalTranslation/Slimefun4-CN pull request #1
Opened 2023-05-21 04:34 UTC by MAG10d

2023-05-21 06:26 UTC, xMikux requested changes

2023-05-21 06:26 UTC, xMikux commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/Slimefun.java
> +            logger.log(Level.INFO, "檢測到你正在使用 Paper 服務端! 性能最佳化已應用.");
```suggestion
            logger.log(Level.INFO, "已偵測到 Paper 伺服器端！效能最佳化已套用。);
```

2023-05-21 06:26 UTC, xMikux commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/Slimefun.java
> +        logger.log(Level.INFO, "正在創建文件夾...");
```suggestion
        logger.log(Level.INFO, "正在建立目錄...");
```

2023-05-21 06:26 UTC, xMikux commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/Slimefun.java
> +        logger.log(Level.INFO, "正在載入資料庫...");
```suggestion
        logger.log(Level.INFO, "載入資料庫...");
```

2023-05-21 06:26 UTC, xMikux commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/Slimefun.java
> +        logger.log(Level.INFO, "正在載入語言文件...");
```suggestion
        logger.log(Level.INFO, "載入語言檔案...");
```

2023-05-21 06:26 UTC, xMikux commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/Slimefun.java
> +        logger.log(Level.INFO, "載入礦物資源...");
```suggestion
        logger.log(Level.INFO, "載入 GEO-資源...");
```

2023-05-21 06:26 UTC, xMikux commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/Slimefun.java
> +        logger.log(Level.INFO, "載入自訂標籤...");
```suggestion
        logger.log(Level.INFO, "載入標籤...");
```

2023-05-21 06:26 UTC, xMikux commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/Slimefun.java
> +        logger.log(Level.INFO, "載入研究項目...");
```suggestion
        logger.log(Level.INFO, "載入研究...");
```

2023-05-21 06:26 UTC, xMikux commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/Slimefun.java
> +        logger.log(Level.INFO, "正在註冊監聽器...");
```suggestion
        logger.log(Level.INFO, "註冊接聽器...");
```

2023-05-21 06:26 UTC, xMikux commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/Slimefun.java
> +        logger.log(Level.INFO, "正在載入第三方插件支持...");
```suggestion
        logger.log(Level.INFO, "載入第三方插件整合...");
```

2023-05-21 06:26 UTC, xMikux commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/Slimefun.java
> +        logger.log(Level.INFO, "Slimefun 完成載入, 耗時 {0}", getStartupTime(timestamp));
```suggestion
        logger.log(Level.INFO, "Slimefun 已完成載入，耗時 {0}", getStartupTime(timestamp));
```

2023-05-21 06:26 UTC, xMikux commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/Slimefun.java
> +                getLogger().log(Level.WARNING, "我們無法識別你正在使用的 Minecraft 版本 (1.{0}.x)", version);
```suggestion
                getLogger().log(Level.WARNING, "我們無法判斷你所使用的 Minecraft 版本？（1.{0}.x）", version);
```

2023-05-21 06:26 UTC, xMikux commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/Slimefun.java
> +            getLogger().log(Level.SEVERE, x, () -> "錯誤: 無法識別伺服器 Minecraft 版本, Slimefun v" + getDescription().getVersion());
```suggestion
            getLogger().log(Level.SEVERE, x, () -> "錯誤：無法判斷環境或 Minecraft 的版本，Slimefun v" + getDescription().getVersion());
```

2023-05-21 06:46 UTC, xMikux requested changes

2023-05-21 06:46 UTC, xMikux commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/StartupWarnings.java
> +        logger.log(Level.SEVERE, PREFIX + "Slimefun 並未被正確安裝!");
```suggestion
        logger.log(Level.SEVERE, PREFIX + "Slimefun 並未被正確安裝！");
```

2023-05-21 06:46 UTC, xMikux commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/StartupWarnings.java
> +        logger.log(Level.SEVERE, PREFIX + "你正在使用不支持的Minecraft版本!");
```suggestion
        logger.log(Level.SEVERE, PREFIX + "你正在使用不支援的 Minecraft 版本！");
```

2023-05-21 06:46 UTC, xMikux commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/StartupWarnings.java
> +        logger.log(Level.SEVERE, PREFIX + "你正在使用Minecraft 1.{0}.x", majorVersion);
```suggestion
        logger.log(Level.SEVERE, PREFIX + "你正在使用 Minecraft 1.{0}.x", majorVersion);
```

2023-05-21 06:46 UTC, xMikux commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/StartupWarnings.java
>          logger.log(Level.SEVERE, PREFIX + "但 Slimefun {0} 只支持", slimefunVersion);
```suggestion
        logger.log(Level.SEVERE, PREFIX + "但 Slimefun {0} 只支援", slimefunVersion);
```

2023-05-21 06:46 UTC, xMikux commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/StartupWarnings.java
> +        logger.log(Level.SEVERE, PREFIX + "Slimefun 並未被正確安裝!");
```suggestion
        logger.log(Level.SEVERE, PREFIX + "Slimefun 並未被正確安裝！");
```

2023-05-21 06:46 UTC, xMikux commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/StartupWarnings.java
> +        logger.log(Level.SEVERE, PREFIX + "CraftBukkit 不再受支持!");
```suggestion
        logger.log(Level.SEVERE, PREFIX + "CraftBukkit 已不再受支援！");
```

2023-05-21 06:46 UTC, xMikux commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/StartupWarnings.java
> +        logger.log(Level.SEVERE, PREFIX + "Slimefun 要求你使用 Spigot, Paper 或");
```suggestion
        logger.log(Level.SEVERE, PREFIX + "Slimefun 需要你使用 Spigot、Paper 或");
```

2023-05-21 06:46 UTC, xMikux commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/StartupWarnings.java
> +        logger.log(Level.SEVERE, PREFIX + "任何Spigot或Paper的受支持分支.");
```suggestion
        logger.log(Level.SEVERE, PREFIX + "任何 Spigot 或 Paper 的受支援分支。");
```

2023-05-21 06:46 UTC, xMikux commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/StartupWarnings.java
> +        logger.log(Level.SEVERE, PREFIX + "(我們推薦 Paper)");
```suggestion
        logger.log(Level.SEVERE, PREFIX + "（我們推薦 Paper）");
```

2023-05-21 06:46 UTC, xMikux commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/StartupWarnings.java
> +        logger.log(Level.WARNING, PREFIX + "你的 Java 版本 (Java {0}) 已過時.", javaVersion);
```suggestion
        logger.log(Level.WARNING, PREFIX + "你的 Java 版本（Java {0}）已過時。", javaVersion);
```

2023-05-21 06:46 UTC, xMikux commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/StartupWarnings.java
> +        logger.log(Level.WARNING, PREFIX + "我們推薦你升級至 Java {0}.", recommendedJavaVersion);
```suggestion
        logger.log(Level.WARNING, PREFIX + "我們推薦你升級到 Java {0}。", recommendedJavaVersion);
```

2023-05-21 06:46 UTC, xMikux commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/StartupWarnings.java
> +        logger.log(Level.WARNING, PREFIX + "它所帶來的新功能.");
```suggestion
        logger.log(Level.WARNING, PREFIX + "它所帶來的新功能。");
```

2023-05-21 06:46 UTC, xMikux commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/StartupWarnings.java
> +        logger.log(Level.WARNING, PREFIX + "在可預見的未來, Slimefun 也將需要 Java {0}", recommendedJavaVersion);
```suggestion
        logger.log(Level.WARNING, PREFIX + "在可預見的未來，Slimefun 也將需要 Java {0}", recommendedJavaVersion);
```

2023-05-21 06:46 UTC, xMikux commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/StartupWarnings.java
> +        logger.log(Level.WARNING, PREFIX + "所以請更新!");
```suggestion
        logger.log(Level.WARNING, PREFIX + "所以請更新！");
```

2023-05-21 06:57 UTC, xMikux requested changes

2023-05-21 06:57 UTC, xMikux commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/Slimefun.java
> +            logger.log(Level.INFO, "已偵測到 Paper 伺服器端！效能最佳化已套用。);
```suggestion
            logger.log(Level.INFO, "已偵測到 Paper 伺服器端！效能最佳化已套用。");
```

2023-05-21 07:23 UTC, xMikux requested changes

2023-05-21 07:23 UTC, xMikux commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/Slimefun.java
> +            logger.log(Level.WARNING, "'networks.max-size' 大小設置錯誤! 它必須大於1, 而你設置的是: {0}", networkSize);
```suggestion
            logger.log(Level.WARNING, "你的「networks.max-size」設定錯誤！必須大於 1，目前設定：{0}", networkSize);
```

2023-05-21 12:12 UTC, xMikux requested changes

2023-05-21 12:12 UTC, xMikux commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/guide/SurvivalSlimefunGuide.java
> +        item = new SlimefunGuideItem(this, "&aSlimefun指南 &7(箱子介面)");
```suggestion
        item = new SlimefunGuideItem(this, "&aSlimefun 指南&7（生存模式）");
```

2023-05-21 12:12 UTC, xMikux commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/guide/SurvivalSlimefunGuide.java
> +        item = new SlimefunGuideItem(this, "&aSlimefun指南 &7(箱子介面)");
```suggestion
        item = new SlimefunGuideItem(this, "&aSlimefun 指南&7（生存模式）");
```

2023-05-21 12:12 UTC, xMikux commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/guide/SurvivalSlimefunGuide.java
> +            menu.addItem(slot, new CustomItemStack(ChestMenuUtils.getBackButton(p, "", "&f左鍵點擊: &7返回上一頁", "&fShift + 左鍵點擊: &7返回主選單")));
```suggestion
            menu.addItem(slot, new CustomItemStack(ChestMenuUtils.getBackButton(p, "", "&f左鍵點擊：&7返回上一頁", "&fShift + 左鍵點擊：&7返回主選單")));
```

2023-05-21 12:12 UTC, xMikux commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/guide/SurvivalSlimefunGuide.java
> +            String lore = hasPermission(p, slimefunItem) ? "&f需要在 " + slimefunItem.getItemGroup().getDisplayName(p) + " 中解鎖" : "&f沒有權限";
```suggestion
            String lore = hasPermission(p, slimefunItem) ? "&f需要在「" + slimefunItem.getItemGroup().getDisplayName(p) + "」中解鎖" : "&f沒有權限";
```

2023-05-21 12:12 UTC, xMikux commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/guide/SurvivalSlimefunGuide.java
> +        p.sendMessage(ChatColor.DARK_RED + "伺服器發生了一個內部錯誤. 請聯絡管理員處理.");
```suggestion
        p.sendMessage(ChatColor.DARK_RED + "伺服器發生了一個內部錯誤。請聯絡管理員處理。");
```

2023-05-21 12:12 UTC, xMikux commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/guide/SurvivalSlimefunGuide.java
> +        Slimefun.logger().log(Level.SEVERE, "在打開指南書裡的 Slimefun 物品時發生了意外!", x);
```suggestion
        Slimefun.logger().log(Level.SEVERE, "在打開指南書裡的 Slimefun 物品時發生了意外！", x);
```

2023-05-21 12:12 UTC, xMikux commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/androids/AndroidFuelSource.java
> +    SOLID("", "&f這機器人需要固態燃料", "&f例如煤炭, 木頭, 等等..."),
```suggestion
    SOLID("", "&f這機器人需要固態燃料", "&f例如煤炭、木頭等等..."),
```

2023-05-21 12:12 UTC, xMikux commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/androids/AndroidFuelSource.java
> +    LIQUID("", "&f這機器人需要液態燃料", "&f例如岩漿, 石油, 燃油, 等等..."),
```suggestion
    LIQUID("", "&f這機器人需要液態燃料", "&f例如熔岩、石油、燃油等等..."),
```

2023-05-21 12:12 UTC, xMikux commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/androids/AndroidFuelSource.java
> +    NUCLEAR("", "&f這機器人需要放射性燃料", "&f例如 鈾, 錼或高純度鈾");
```suggestion
    NUCLEAR("", "&f這機器人需要放射性燃料", "&f例如鈾、錼或高純度鈾");
```

2023-05-21 12:21 UTC, xMikux requested changes

2023-05-21 12:21 UTC, xMikux commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/guide/CheatSheetSlimefunGuide.java
> +        item = new SlimefunGuideItem(this, "&cSlimefun指南 &4(作弊介面)");
```suggestion
        item = new SlimefunGuideItem(this, "&cSlimefun 指南&4（作弊模式）");
```

2023-05-21 12:31 UTC, weiii-joe requested changes

2023-05-21 12:31 UTC, weiii-joe commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/androids/Script.java
> +        lore.add("&7評價: " + getScriptRatingPercentage());
```suggestion
        lore.add("&7評價：" + getScriptRatingPercentage());
```

2023-05-21 12:31 UTC, weiii-joe commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/androids/Script.java
> +        lore.add("&7下載量: &f" + getDownloads());
```suggestion
        lore.add("&7下載量：&f" + getDownloads());
```

2023-05-21 12:31 UTC, weiii-joe commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/androids/ProgrammableAndroid.java
> +        menu.addItem(5, new CustomItemStack(HeadTexture.SCRIPT_DOWN.getAsItemStack(), "&6> 下載程式", "", "&e從伺服器上下載玩家上傳的程式", "&e可以下載就用,或修改後再使用"));
```suggestion
        menu.addItem(5, new CustomItemStack(HeadTexture.SCRIPT_DOWN.getAsItemStack(), "&6> 下載程式", "", "&e從伺服器上下載玩家上傳的程式", "&e可以下載就用，或修改後再使用"));
```

2023-05-21 13:04 UTC, xMikux requested changes

2023-05-21 13:04 UTC, xMikux commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/androids/ProgrammableAndroid.java
> +        menu.addItem(3, new CustomItemStack(HeadTexture.SCRIPT_NEW.getAsItemStack(), "&4> 創建新程式", "", "&c刪除你目前正在使用的程式", "&c並創建一個全新空白程式"));
```suggestion
        menu.addItem(3, new CustomItemStack(HeadTexture.SCRIPT_NEW.getAsItemStack(), "&4> 建立新程式", "", "&c刪除你目前正在使用的程式", "&c並建立一個全新空白程式"));
```

2023-05-21 13:04 UTC, xMikux commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/androids/Script.java
> +        lore.add("&4(這將會把目前的程式覆蓋掉!)");
```suggestion
        lore.add("&4（這將會把目前的程式覆蓋掉！）");
```

2023-05-21 14:24 UTC, xMikux requested changes

2023-05-21 14:24 UTC, xMikux commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/SlimefunItems.java
> +    public static final SlimefunItemStack BROKEN_SPAWNER = new SlimefunItemStack("BROKEN_SPAWNER", Material.SPAWNER, "&c已損壞的生怪磚", "&7類型: &b<Type>", "", "&c你必須用「古代祭壇」修復");
```suggestion
    public static final SlimefunItemStack BROKEN_SPAWNER = new SlimefunItemStack("BROKEN_SPAWNER", Material.SPAWNER, "&c已損壞的生怪磚", "&7類型：&b<類型>", "", "&c你必須用「古代祭壇」修復");
```

2023-05-21 14:24 UTC, xMikux commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/SlimefunItems.java
> +    public static final SlimefunItemStack REPAIRED_SPAWNER = new SlimefunItemStack("REINFORCED_SPAWNER", Material.SPAWNER, "&b已修復的生怪磚", "&7類型: &b<Type>");
```suggestion
    public static final SlimefunItemStack REPAIRED_SPAWNER = new SlimefunItemStack("REINFORCED_SPAWNER", Material.SPAWNER, "&b已修復的生怪磚", "&7類型：&b<類型>");
```

2023-05-21 14:24 UTC, xMikux commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/SlimefunItems.java
> +    public static final SlimefunItemStack REINFORCED_CLOTH = new SlimefunItemStack("REINFORCED_CLOTH", Material.PAPER, "&b加強布", "", "&f這塊布已經用&b鉛&f加固", "&f以防止放射性物質");
```suggestion
    public static final SlimefunItemStack REINFORCED_CLOTH = new SlimefunItemStack("REINFORCED_CLOTH", Material.PAPER, "&b加強布", "", "&f這塊布已經用&b鉛&f加固", "&f以防止放射性物質洩漏");
```

2023-05-21 14:24 UTC, xMikux commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/SlimefunItems.java
> +    public static final SlimefunItemStack ELYTRA_CAP = new SlimefunItemStack("ELYTRA_CAP", Material.LEATHER_HELMET, Color.PURPLE, "&5鞘翅帽", "", "&7這個帽子可以保護你免受於", "&7鞘翅飛行時墜毀.");
```suggestion
    public static final SlimefunItemStack ELYTRA_CAP = new SlimefunItemStack("ELYTRA_CAP", Material.LEATHER_HELMET, Color.PURPLE, "&5鞘翅帽", "", "&7這個帽子可以保護你免受於", "&7鞘翅飛行時墜毀");
```

2023-05-21 14:24 UTC, xMikux commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/SlimefunItems.java
> +    public static final SlimefunItemStack RAG = new SlimefunItemStack("RAG", Material.PAPER, "&c紗布", "", "&a一級醫療用品", "", "&f恢復2顆心", "&f滅火", "", LoreBuilder.RIGHT_CLICK_TO_USE);
```suggestion
    public static final SlimefunItemStack RAG = new SlimefunItemStack("RAG", Material.PAPER, "&c紗布", "", "&a一級醫療用品", "", "&f恢復 2 顆心", "&f滅火", "", LoreBuilder.RIGHT_CLICK_TO_USE);
```

2023-05-21 14:24 UTC, xMikux commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/SlimefunItems.java
> +    public static final SlimefunItemStack BANDAGE = new SlimefunItemStack("BANDAGE", Material.PAPER, "&c繃帶", "", "&a二級醫療用品", "", "&f恢復4顆心", "&f滅火", "", LoreBuilder.RIGHT_CLICK_TO_USE);
```suggestion
    public static final SlimefunItemStack BANDAGE = new SlimefunItemStack("BANDAGE", Material.PAPER, "&c繃帶", "", "&a二級醫療用品", "", "&f恢復 4 顆心", "&f滅火", "", LoreBuilder.RIGHT_CLICK_TO_USE);
```

2023-05-21 14:24 UTC, xMikux commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/SlimefunItems.java
> +    public static final SlimefunItemStack SPLINT = new SlimefunItemStack("SPLINT", Material.STICK, "&c夾板", "", "&a一級醫療用品", "", "&f恢復2顆心", "", LoreBuilder.RIGHT_CLICK_TO_USE);
```suggestion
    public static final SlimefunItemStack SPLINT = new SlimefunItemStack("SPLINT", Material.STICK, "&c夾板", "", "&a一級醫療用品", "", "&f恢復 2 顆心", "", LoreBuilder.RIGHT_CLICK_TO_USE);
```

2023-05-21 14:24 UTC, xMikux commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/SlimefunItems.java
> +    public static final SlimefunItemStack VITAMINS = new SlimefunItemStack("VITAMINS", Material.NETHER_WART, "&c維他命", "", "&a三級醫療用品", "", "&f恢復4顆心", "&f滅火", "&f治癒中毒/凋零/放射", "", LoreBuilder.RIGHT_CLIC
```suggestion
    public static final SlimefunItemStack VITAMINS = new SlimefunItemStack("VITAMINS", Material.NETHER_WART, "&c維他命", "", "&a三級醫療用品", "", "&f恢復 4 顆心", "&f滅火", "&f治癒中毒、凋零、放射", "", LoreBuilder.RIGHT_CLICK_TO_USE);
```

2023-05-21 14:24 UTC, xMikux commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/SlimefunItems.java
> +    public static final SlimefunItemStack MEDICINE = new SlimefunItemStack("MEDICINE", Material.POTION, Color.RED, "&c醫療品", "", "&a三級醫療用品", "", "&f恢復4顆心", "&f滅火", "&f治癒中毒/凋零/放射");
```suggestion
    public static final SlimefunItemStack MEDICINE = new SlimefunItemStack("MEDICINE", Material.POTION, Color.RED, "&c醫療品", "", "&a三級醫療用品", "", "&f恢復 4 顆心", "&f滅火", "&f治癒中毒、凋零、放射");
```

2023-05-21 14:24 UTC, xMikux commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/SlimefunItems.java
> +    public static final SlimefunItemStack FLASK_OF_KNOWLEDGE = new SlimefunItemStack("FLASK_OF_KNOWLEDGE", Material.GLASS_BOTTLE, "&c學識之瓶", "", "&f你可以把一些經驗", "&f存在瓶子裡", "&7消耗: &a1 個等級");
```suggestion
    public static final SlimefunItemStack FLASK_OF_KNOWLEDGE = new SlimefunItemStack("FLASK_OF_KNOWLEDGE", Material.GLASS_BOTTLE, "&c學識之瓶", "", "&f你可以把一些經驗", "&f儲存到瓶子裡", "&7消耗：&a1 等經驗等級");
```

2023-05-21 14:24 UTC, xMikux commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/SlimefunItems.java
> +    public static final SlimefunItemStack BACKPACK_SMALL = new SlimefunItemStack("SMALL_BACKPACK", HeadTexture.BACKPACK, "&e小背包", "", "&7大小: &e9格", PlayerBackpack.LORE_OWNER, "", LoreBuilder.RIGHT_CL
```suggestion
    public static final SlimefunItemStack BACKPACK_SMALL = new SlimefunItemStack("SMALL_BACKPACK", HeadTexture.BACKPACK, "&e小背包", "", "&7大小：&e9 格", PlayerBackpack.LORE_OWNER, "", LoreBuilder.RIGHT_CLICK_TO_OPEN);
```

2023-05-21 14:24 UTC, xMikux commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/SlimefunItems.java
> +    public static final SlimefunItemStack BACKPACK_MEDIUM = new SlimefunItemStack("MEDIUM_BACKPACK", HeadTexture.BACKPACK, "&e背包", "", "&7大小: &e18格", PlayerBackpack.LORE_OWNER, "", LoreBuilder.RIGHT_
```suggestion
    public static final SlimefunItemStack BACKPACK_MEDIUM = new SlimefunItemStack("MEDIUM_BACKPACK", HeadTexture.BACKPACK, "&e背包", "", "&7大小：&e18 格", PlayerBackpack.LORE_OWNER, "", LoreBuilder.RIGHT_CLICK_TO_OPEN);
```

2023-05-21 14:24 UTC, xMikux commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/SlimefunItems.java
> +    public static final SlimefunItemStack BACKPACK_LARGE = new SlimefunItemStack("LARGE_BACKPACK", HeadTexture.BACKPACK, "&e大背包", "", "&7大小: &e27格(1個箱子)", PlayerBackpack.LORE_OWNER, "", LoreBuilder.R
```suggestion
    public static final SlimefunItemStack BACKPACK_LARGE = new SlimefunItemStack("LARGE_BACKPACK", HeadTexture.BACKPACK, "&e大背包", "", "&7大小：&e27 格", PlayerBackpack.LORE_OWNER, "", LoreBuilder.RIGHT_CLICK_TO_OPEN);
```

2023-05-21 14:24 UTC, xMikux commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/SlimefunItems.java
> +    public static final SlimefunItemStack WOVEN_BACKPACK = new SlimefunItemStack("WOVEN_BACKPACK", HeadTexture.BACKPACK, "&e編織背包", "", "&7大小: &e36格", PlayerBackpack.LORE_OWNER, "", LoreBuilder.RIGHT_
```suggestion
    public static final SlimefunItemStack WOVEN_BACKPACK = new SlimefunItemStack("WOVEN_BACKPACK", HeadTexture.BACKPACK, "&e編織背包", "", "&7大小：&e36 格", PlayerBackpack.LORE_OWNER, "", LoreBuilder.RIGHT_CLICK_TO_OPEN);
```

2023-05-21 14:24 UTC, xMikux commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/SlimefunItems.java
> +    public static final SlimefunItemStack GILDED_BACKPACK = new SlimefunItemStack("GILDED_BACKPACK", HeadTexture.BACKPACK, "&e鍍金背包", "", "&7大小: &e45格", PlayerBackpack.LORE_OWNER, "", LoreBuilder.RIGH
```suggestion
    public static final SlimefunItemStack GILDED_BACKPACK = new SlimefunItemStack("GILDED_BACKPACK", HeadTexture.BACKPACK, "&e鍍金背包", "", "&7大小：&e45 格", PlayerBackpack.LORE_OWNER, "", LoreBuilder.RIGHT_CLICK_TO_OPEN);
```

2023-05-21 14:24 UTC, xMikux commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/SlimefunItems.java
> +    public static final SlimefunItemStack RADIANT_BACKPACK = new SlimefunItemStack("RADIANT_BACKPACK", HeadTexture.BACKPACK, "&e登山背包", "", "&7大小: &e54格 (2個箱子)", PlayerBackpack.LORE_OWNER, "", LoreBui
```suggestion
    public static final SlimefunItemStack RADIANT_BACKPACK = new SlimefunItemStack("RADIANT_BACKPACK", HeadTexture.BACKPACK, "&e登山背包", "", "&7大小：&e54 格", PlayerBackpack.LORE_OWNER, "", LoreBuilder.RIGHT_CLICK_TO_OPEN);
```

2023-05-21 14:24 UTC, xMikux commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/SlimefunItems.java
> +    public static final SlimefunItemStack BOUND_BACKPACK = new SlimefunItemStack("BOUND_BACKPACK", HeadTexture.ENDER_BACKPACK, "&c靈魂綁定背包", "", "&7大小: &e36格", PlayerBackpack.LORE_OWNER, "", LoreBuilde
```suggestion
    public static final SlimefunItemStack BOUND_BACKPACK = new SlimefunItemStack("BOUND_BACKPACK", HeadTexture.ENDER_BACKPACK, "&c靈魂綁定背包", "", "&7大小：&e36 格", PlayerBackpack.LORE_OWNER, "", LoreBuilder.RIGHT_CLICK_TO_OPEN);
```

2023-05-21 14:24 UTC, xMikux commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/SlimefunItems.java
> +    public static final SlimefunItemStack COOLER = new SlimefunItemStack("COOLER", HeadTexture.COOLER, "&b冰箱", "&f只能儲存果汁/冰沙", "&f並在飢餓時自動消耗", "&f只有放在你的背包才有效", "", "&7大小: &e27格", PlayerBackpack.LORE_OW
```suggestion
    public static final SlimefunItemStack COOLER = new SlimefunItemStack("COOLER", HeadTexture.COOLER, "&b冰箱", "&f只能儲存果汁、冰沙", "&f並在飢餓時自動消耗", "&f只有放在你的背包中才有效", "", "&7大小：&e27 格", PlayerBackpack.LORE_OWNER, "", LoreBuilder.RIGHT_CLICK_TO_OPEN);
```

2023-05-21 14:51 UTC, xMikux requested changes

2023-05-21 14:51 UTC, xMikux commented on src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/androids/Script.java
>          lore.add("&a" + getUpvotes() + " \u263A &7| &4\u2639 " + getDownvotes());
```suggestion
        lore.add("&a" + getUpvotes() + " \u263A&7｜&4\u2639 " + getDownvotes());
```

2023-05-24 06:06 UTC, xMikux requested changes

2023-05-24 06:06 UTC, xMikux commented on src/main/resources/languages/zh-TW/resources.yml
> +    nether_ice: '地域冰'
```suggestion
    nether_ice: '地獄冰'
```

2023-05-28 06:59 UTC, xMikux approved these changes

2023-05-28 14:14 UTC, weiii-joe requested changes

2023-05-28 14:14 UTC, weiii-joe commented on src/main/java/io/github/thebusybiscuit/slimefun4/utils/LoreBuilder.java
> +        return "&7&o恢复 &b&o" + hungerFormat.format(value) + " &7&o飽食度";
```suggestion
        return "&7&o恢復 &b&o" + hungerFormat.format(value) + " &7&o飽食度";
```

2023-06-12 15:21 UTC, weiii-joe approved these changes

2023-06-12 15:57 UTC, xMikux approved these changes

2023-06-12 15:57 UTC, merged